package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gorilla/mux"
	"github.com/zoff-music/vibes/vibe"
	"golang.org/x/crypto/bcrypt"
)

// CreateRoom handles POST /api/v1/rooms
func CreateRoom(
	db vibe.RoomCreator,
) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		var req vibe.CreateRoomRequest
		err := json.NewDecoder(r.Body).Decode(&req)
		if err != nil {
			handleError(w, fmt.Errorf("invalid request body: %w", err), http.StatusBadRequest, true)
			return
		}

		if req.Name == "" {
			handleError(w, fmt.Errorf("room name is required"), http.StatusBadRequest, false)
			return
		}

		// Check if room already exists
		existingRoom, err := db.GetRoomByName(ctx, req.Name)
		if err == nil && !existingRoom.IsEmpty() {
			// Room exists, return it with 200 OK
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			_ = json.NewEncoder(w).Encode(existingRoom)
			return
		}

		var passwordHash string
		if req.Password != "" {
			hash, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
			if err != nil {
				handleError(w, fmt.Errorf("failed to hash password: %w", err), http.StatusInternalServerError, true)
				return
			}
			passwordHash = string(hash)
		}

		room := &vibe.Room{
			// ID is generated by DB
			Name:              req.Name,
			AdminPasswordHash: passwordHash,
			HasPassword:       passwordHash != "",
			Settings:          vibe.DefaultRoomSettings(),
			CreatedAt:         time.Now(),
		}

		created, err := db.CreateRoom(ctx, room)
		if err != nil {
			handleError(w, fmt.Errorf("failed to create room: %w", err), http.StatusInternalServerError, true)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(created)
	}
}

// GetRoom handles GET /api/v1/rooms/:id
func GetRoom(
	db vibe.RoomFetcher,
) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		vars := mux.Vars(r)
		roomID := vars["id"]

		room, err := db.GetRoom(ctx, roomID)
		if err != nil {
			handleError(w, fmt.Errorf("failed to fetch room: %w", err), http.StatusInternalServerError, true)
			return
		}

		if room.IsEmpty() {
			handleError(w, fmt.Errorf("room not found"), http.StatusNotFound, false)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(room)
	}
}

// UpdateRoom handles PATCH /api/v1/rooms/:id
func UpdateRoom(
	db vibe.RoomUpdater,
) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		vars := mux.Vars(r)
		roomID := vars["id"]

		// TODO: Implement admin authorization check
		// For now, we assume the user is authorized if they are an admin in their session

		var req vibe.UpdateRoomRequest
		err := json.NewDecoder(r.Body).Decode(&req)
		if err != nil {
			handleError(w, fmt.Errorf("invalid request body: %w", err), http.StatusBadRequest, true)
			return
		}

		room, err := db.GetRoom(ctx, roomID)
		if err != nil {
			handleError(w, fmt.Errorf("failed to fetch room: %w", err), http.StatusInternalServerError, true)
			return
		}

		if room.IsEmpty() {
			handleError(w, fmt.Errorf("room not found"), http.StatusNotFound, false)
			return
		}

		room.Settings = req.Settings
		updated, err := db.UpdateRoom(ctx, room)
		if err != nil {
			handleError(w, fmt.Errorf("failed to update room: %w", err), http.StatusInternalServerError, true)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(updated)
	}
}

// CreateSession handles POST /api/v1/rooms/:id/sessions
func CreateSession(
	db vibe.SessionCreator,
) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		vars := mux.Vars(r)
		roomID := vars["id"]

		var req vibe.CreateSessionRequest
		err := json.NewDecoder(r.Body).Decode(&req)
		if err != nil {
			handleError(w, fmt.Errorf("invalid request body: %w", err), http.StatusBadRequest, true)
			return
		}

		room, err := db.GetRoom(ctx, roomID)
		if err != nil {
			handleError(w, fmt.Errorf("failed to fetch room: %w", err), http.StatusInternalServerError, true)
			return
		}

		if room.IsEmpty() {
			handleError(w, fmt.Errorf("room not found"), http.StatusNotFound, false)
			return
		}

		isAdmin := false
		if req.Password != "" && room.AdminPasswordHash != "" {
			err = bcrypt.CompareHashAndPassword([]byte(room.AdminPasswordHash), []byte(req.Password))
			if err == nil {
				isAdmin = true
			}
		}

		user := &vibe.User{
			// ID is generated by DB
			RoomID:     roomID,
			Nickname:   &req.Nickname,
			IsAdmin:    isAdmin,
			JoinedAt:   time.Now(),
			LastSeenAt: time.Now(),
		}

		createdUser, err := db.CreateUser(ctx, user)
		if err != nil {
			handleError(w, fmt.Errorf("failed to create session: %w", err), http.StatusInternalServerError, true)
			return
		}

		resp := vibe.SessionResponse{
			UserID:   createdUser.ID,
			Nickname: createdUser.Nickname,
			IsAdmin:  createdUser.IsAdmin,
			Room:     room,
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(resp)
	}
}
