// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/rooms/create": {
    params: {};
  };
  "/rooms/:id": {
    params: {
      "id": string;
    };
  };
  "/callback": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/rooms/create" | "/rooms/:id" | "/callback" | "/admin";
  };
  "./routes/_index/route.tsx": {
    id: "routes/_index/route";
    page: "/";
  };
  "./routes/rooms.create/route.tsx": {
    id: "routes/rooms.create/route";
    page: "/rooms/create";
  };
  "./routes/rooms.$id/route.tsx": {
    id: "routes/rooms.$id/route";
    page: "/rooms/:id";
  };
  "./routes/callback/route.tsx": {
    id: "routes/callback/route";
    page: "/callback";
  };
  "./routes/admin/route.tsx": {
    id: "routes/admin/route";
    page: "/admin";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index/route": typeof import("./src/./routes/_index/route.tsx");
  "routes/rooms.create/route": typeof import("./src/./routes/rooms.create/route.tsx");
  "routes/rooms.$id/route": typeof import("./src/./routes/rooms.$id/route.tsx");
  "routes/callback/route": typeof import("./src/./routes/callback/route.tsx");
  "routes/admin/route": typeof import("./src/./routes/admin/route.tsx");
};