name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_call:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install Dependencies
      run: bun install
      
    - name: Typecheck
      run: bun run typecheck
      
    - name: Lint
      run: bun run lint
      
    - name: Build
      run: bun run build

  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'backend/go.mod'
        
    - name: Build
      run: make build
      
    - name: Test
      run: make test

  migrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'backend/go.mod'
        
    - name: Create data dir
      run: mkdir -p backend/data
      
    - name: Build Migrator
      run: make build-migrator
      
    - name: Run Up Migrations
      run: make migrate-up
      
    - name: Run Down Migrations
      run: make migrate-down STEPS=1000

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker Compose
      run: docker compose build
